# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.3
language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/SimpleREST.xcworkspace
xcode_scheme: SimpleREST-Example
xcode_sdk: iphonesimulator12.4
script:
- xcodebuild clean build test -workspace Example/SimpleREST.xcworkspace -scheme SimpleREST-Example -destination "platform=iOS Simulator,name=iPhone Xs,OS=12.4" CODE_SIGNING_REQUIRED=NO
