# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
podfile: Example/Podfile
xcode_workspace: Example/SimpleREST.xcworkspace
xcode_scheme: SimpleREST-Example
xcode_sdk: iphonesimulator9.3
script:
- xcodebuild clean build test -workspace Example/SimpleREST.xcworkspace -scheme SimpleREST-Example -destination "platform=iOS Simulator,name=iPhone 7,OS=11.0" CODE_SIGNING_REQUIRED=NO
